@extends('publik.layouts.main')

@section('container')
    <div class="py-4 container-fluid">
        <div class="row justify-content-center">
            <!-- Calendar Section -->
            <div class="col-12 col-lg-8">
                <div class="calendar-section">
                    <h2 class="mb-4 text-center">Jadwal Kegiatan</h2>
                    <div class="calendar-wrapper">
                        <div id="calendar" class="bg-white rounded-lg shadow">
                            <div class="mb-3 calendar-header d-flex justify-content-between align-items-center">
                                <button id="prev" class="btn btn-link text-dark">&lt;</button>
                                <h2 id="monthYear" class="mb-0 h5"></h2>
                                <button id="next" class="btn btn-link text-dark">&gt;</button>
                            </div>
                            <div class="mb-2 calendar-days">
                                <div class="text-center row g-0">
                                    <div class="col">Min</div>
                                    <div class="col">Sen</div>
                                    <div class="col">Sel</div>
                                    <div class="col">Rab</div>
                                    <div class="col">Kam</div>
                                    <div class="col">Jum</div>
                                    <div class="col">Sab</div>
                                </div>
                            </div>
                            <div id="dates">
                                <!-- Dates will be generated by JavaScript -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <p style="color: red; width: 100%; text-align: center; margin-top: 1.5rem; font-size: 0.8rem;">*Note: Klik
                tanggal yang berwarna biru untuk mengetahui acara/kegiatan yang (telah, sedang, akan) berjalan di MKKS
                Bekasi</p>
        </div>
    </div>

    <!-- Modal Events -->
    <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="eventModalLabel">Detail Acara</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="eventDetails">
                    <!-- Event details will be filled by JavaScript -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>

    @php
        $events = DB::table('calendar')->select('event_name', 'event_date')->get();
        $eventsArray = [];
        foreach ($events as $event) {
            $eventsArray[$event->event_date][] = $event->event_name;
        }
    @endphp

    <script>
        const events = @json($eventsArray);
    </script>
    <script src="{{ asset('js/jadwal.js') }}"></script>
@endsection
